### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@holtkamp thanks a lot for your contribution!

Can you please add PHP 8 to the GitHub Actions CI workflow?

Thanks!

**Comment by holtkamp** [comment]
@sagikazarmark yeah I can give it a try. 

When multiple versions are involved, it seems something like this "version build matrix approach" would make life easier?

https://github.com/marketplace/actions/setup-php-action#matrix-setup
https://github.com/Ocramius/DoctrineBatchUtils/blob/8affefde661133a385c2416dcb63277e77e1913b/.github/workflows/phpunit.yml

I don't have experience with it, but I read about it in a few twitter posts, might be worth trying?

**Comment by sagikazarmark** [comment]
I'm not entirely sure what you mean. You should just add `, '8.0'` here: https://github.com/bernardphp/drivers/blob/master/.github/workflows/ci.yaml#L41

And fix any issues that may rise. Chances are some dependencies will have to be updated.

**Comment by holtkamp** [comment]
Ah, ok. 

I suggested it due to https://github.com/bernardphp/drivers/blob/c1a2696672efc2471d69c1b849a4d32a91806312/.github/workflows/ci.yaml#L18

But that is the "lowest build" if I am correct. Nevermind!

**Comment by sagikazarmark** [comment]
That's why I linked you here: https://github.com/bernardphp/drivers/blob/master/.github/workflows/ci.yaml#L41

😄

**Comment by holtkamp** [comment]
@sagikazarmark seems to work now, needed to bump PHPUnit as well. 

Can you squash my commits into one? GitHub allows to do that and I never succeeded into doing this manually without messing up the pull request..

**Review by sagikazarmark — APPROVED** [review]
Looks good, thanks!

**Comment by sagikazarmark** [comment]
Damn, forgot squashing

**Comment by sagikazarmark** [comment]
Removed it manually

**Comment by holtkamp** [comment]
>Removed it manually

jealous on such skills 😄 

Thanks for the quick follow-ups!

**Pull request merged**
